return {
	"WhoIsSethDaniel/mason-tool-installer.nvim",
	cmd = { "MasonToolsInstall", "MasonToolsUpdate", "MasonToolsClean" },
	opts = {
		ensure_installed = {
			"bash-debug-adapter",
			"bash-language-server",
			"clangd",
			"cspell",
			"debugpy",
			"delve",
			"dockerls",
			"docker-compose-language-service",
			"dockerfile-language-server",
			"gofumpt",
			"goimports",
			"goimports-reviser",
			"gomodifytags",
			"gopls",
			"js-debug-adapter",
			"jdtls",
			"json-lsp",
			"lua-language-server",
			"markdownlint",
			-- "marksman", use markdown.nvim
			"prettier",
			"prettierd",
			"pyright",
			"shfmt",
			"stylua",
			"sqlfmt",
			"typescript-language-server",
			"yaml-language-server",
		},
	},
}
